### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by colin4k** [ppisljar/pdf_translator#12]
2024-07-12 14:34:20 width: 1188, height: 71, fs: 35.5
2024-07-12 14:34:20 width: 787, height: 61, fs: 61.0
2024-07-12 14:34:20 width: 650, height: 63, fs: 63.0
2024-07-12 14:34:20 INFO:     127.0.0.1:38472 - "POST /translate_pdf/ HTTP/1.1" 500 Internal Server Error
2024-07-12 14:34:20 ERROR:    Exception in ASGI application
2024-07-12 14:34:20 Traceback (most recent call last):
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
2024-07-12 14:34:20     result = await app(  # type: ignore[func-returns-value]
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-12 14:34:20     return await self.app(scope, receive, send)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
2024-07-12 14:34:20     await super().__call__(scope, receive, send)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
2024-07-12 14:34:20     await self.middleware_stack(scope, receive, send)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-12 14:34:20     raise exc
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-12 14:34:20     await self.app(scope, receive, _send)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-12 14:34:20     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-12 14:34:20     raise exc
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-12 14:34:20     await app(scope, receive, sender)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 756, in __call__
2024-07-12 14:34:20     await self.middleware_stack(scope, receive, send)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 776, in app
2024-07-12 14:34:20     await route.handle(scope, receive, send)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle
2024-07-12 14:34:20     await self.app(scope, receive, send)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app
2024-07-12 14:34:20     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-12 14:34:20     raise exc
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-12 14:34:20     await app(scope, receive, sender)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 72, in app
2024-07-12 14:34:20     response = await func(request)
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 278, in app
2024-07-12 14:34:20     raw_response = await run_endpoint_function(
2024-07-12 14:34:20   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-07-12 14:34:20     return await dependant.call(**values)
2024-07-12 14:34:20   File "/app/server.py", line 91, in translate_pdf
2024-07-12 14:34:20     self._translate_pdf(input_pdf_data, self.temp_dir_name, from_lang, to_lang, p_from, p_to, side_by_side)
2024-07-12 14:34:20   File "/app/server.py", line 143, in _translate_pdf
2024-07-12 14:34:20     result = font_engine.get_all_fonts(result)
2024-07-12 14:34:20   File "/app/modules/font/simple.py", line 18, in get_all_fonts
2024-07-12 14:34:20     family, size, ygain = self.get_font_info(image, line.line_cnt)
2024-07-12 14:34:20   File "/app/modules/font/simple.py", line 30, in get_font_info
2024-07-12 14:34:20     font_size = height / line_cnt
2024-07-12 14:34:20 ZeroDivisionError: division by zero

**Comment by cakebomb999** [comment]
i have the same error, how did you fix?
