### ISSUE TITLE
Checkpoint models/unilm/publaynet_dit-b_cascade.pth not found!

### ISSUE THREAD

**Issue by spookey0188** [ppisljar/pdf_translator#8]
I'm encountering this error when running server.py on Windows WSL Kali linux distro build on a RTX 4070 after following all the necessary steps. The error I get is this:

```
Traceback (most recent call last):
  File "/home/kali/pdf_translator/server.py", line 26, in <module>
    layout_engine = load_layout_engine(cfg['layout'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/pdf_translator/modules/__init__.py", line 21, in load_layout_engine
    engine.init(cfg)
  File "/home/kali/pdf_translator/modules/layout/ditod.py", line 11, in init
    self.layout_model = LayoutAnalyzer(
                        ^^^^^^^^^^^^^^^
  File "/home/kali/pdf_translator/utils/layout_model.py", line 40, in __init__
    self.predictor = self._load_model(model_root_dir, device=device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/pdf_translator/utils/layout_model.py", line 112, in _load_model
    return DefaultPredictor(cfg)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/pdf_translator/lib/python3.11/site-packages/detectron2/engine/defaults.py", line 288, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/home/kali/pdf_translator/lib/python3.11/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 62, in load
    ret = super().load(path, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/pdf_translator/lib/python3.11/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint models/unilm/publaynet_dit-b_cascade.pth not found!
```

How do I resolve this?

**Comment by tuha1994** [comment]
how to fix this issue?
