### ISSUE TITLE
Error when run python server.py

### ISSUE THREAD

**Issue by MrVanQish** [ppisljar/pdf_translator#9]
Traceback (most recent call last):
  File "/home/vanqish/Desktop/pdf_translator/server.py", line 25, in <module>
    translator = load_translator(cfg['translator'])
  File "/home/vanqish/Desktop/pdf_translator/modules/__init__.py", line 5, in load_translator
    from .translate.openai_gpt import TranslateOpenAIGPT
  File "/home/vanqish/Desktop/pdf_translator/modules/translate/openai_gpt.py", line 2, in <module>
    from openai import OpenAI
ImportError: cannot import name 'OpenAI' from 'openai' (/home/vanqish/Desktop/pdf_translator/lib/python3.10/site-packages/openai/__init__.py)

**Comment by shopulatov** [comment]
Upgrading openai library using pip worked for me:
`pip install --upgrade openai`
